server:
  port: 28000
spring:
  application:
    name: spring-boot-admin
  mail:
    host: smtp.126.com
    username: wrong1111@126.com
    password: Wyong123
    properties:
      mail.debug: false
      mail.smtp.auth: true
  boot:
    admin:
      notify:
        mail:
          to: 343886028@qq.com
          from: wrong1111@126.com
#          ignore-changes: UNKNOWN:UP
          ignore-changes:
            -
              "*:UP" #从任何状态到up状态都不要发邮件通知
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka01:28761/eureka/,http://eureka02:28762/eureka/
management:
  security:
    enabled: false
info:
  version: @project.version@