server:
  port: 28010
security:
  user:
    name: user
    password: password
  basic:
    enabled: true
management:
  security:
    enabled: false

spring:
  application:
    name: simple-consumer-movie
  boot:
      admin:
        url: http://localhost:28000
        client:
          name: ${spring.application.name}:${server.port}
        enabled: true
        username: ${security.user.name}
        password: ${security.user.password}


eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://user:password@eureka01:28761/eureka/,http://user:password@eureka02:28762/eureka/,http://user:password@eureka03:28763/eureka/
      healthcheck:
          enabled: true
    fetch-registry: true
          
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 10
