security:
  user:
    name: user
    password: password
  basic:
    enabled: true
management:
  security:
    enabled: true
info:
  app:
    name: ${project.name}
    encoding:  ${project.build.sourceEncoding}
    java:
      source: ${java.version}
      target: ${java.version}


spring:
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    
    hibernate:
      ddl-auto: none

  datasource:
   # platform: mysql
#    schema: classpath:schema.sql
#    data: classpath:data.sql

    url: jdbc:mysql://120.24.238.236:3306/shiro
    username: shiro
    password: shiro123456
    driver-class-name: com.mysql.jdbc.Driver
    
  application:
    name: simple-provider-user
  boot:
    admin:
      url: http://localhost:8000
      client:
        name: ${spring.application.name}:${server.port}
      enabled: true
      username: ${security.user.name}
      password: ${security.user.password}

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.example: DEBUG

 
  client:
    service-url:
      defaultZone: http://user:password@eureka01:28761/eureka/,http://user:password@eureka02:28762/eureka/,http://user:password@eureka03:28763/eureka/
      healthcheck:
          enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}


