
info:
  app:
    name: ${project.artifactid}
    encoding:  ${project.build.sourceencoding}
    java:
      source: ${java.version}
      target: ${java.version}


spring:
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    
    hibernate:
      ddl-auto: none

  datasource:
   # platform: mysql
#    schema: classpath:schema.sql
#    data: classpath:data.sql

    url: jdbc:mysql://120.24.238.236:3306/shiro
    username: shiro
    password: shiro123456
    driver-class-name: com.mysql.jdbc.Driver
    
  application:
    name: simple-provider-user
    
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.example: DEBUG

 

eureka:
  server:
    port: 8761
    hostname: eureka01

  client:
    service-url:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
      healthcheck:
          enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}

