

spring:
  application:
    name: eureka01
  profiles: eureka01

server:
  port: 28761
  

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
          user.name: ${security.user.name}
          user.password: ${security.user.password}
    hostname: eureka01
    #perferIpAddress: true
    #ipAdress: 127.0.0.1
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@eureka02:28762/eureka/,http://${security.user.name}:${security.user.password}@eureka03:28763/eureka/
    register-with-eureka: false
    fetch-registry: false
