spring:
  profiles: eureka02
 
 
server:
  port: 8762
eureka:
  instance:
    metadata-map:
      zone: beijing
    hostname: eureka02
    perferIpAddress: true
    ipAdress: 127.0.0.1
    
  client:
    serviceUrl:
      defaultZone:  http://eureka01:8761/eureka/
