security:
  user:
    name: user
    password: password
management:
  security:
    enabled: false

spring:
  application:
    name: simple-discovery-eureka-ha
  freemarker:
    prefer-file-system-access: false
  boot:
    admin:
      client:
        name: ${spring.application.name}:${server.port}
        enabled: true
      url: http://localhost:28000
      username: ${security.user.name}
      password: ${security.user.password}





 