server:
  port: 8010

spring:
  application:
    name: simple-consumer-movie

eureka:
  server:
    port: 8761
    hostname: eureka01

  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
      healthcheck:
          enabled: true
          
  instance:
    prefer-ip-address: true 
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    leaseRenewalIntervalInSeconds: 10
